---
- hosts: localhost
  gather_facts: false
  vars:
    stackname: drone
    region: us-west-2
    account: 601394826940
    drone_version: 1.0.0-rc.4
    cert_id: 727e9900-8f50-4ba8-8bce-09ab4be1e2a2
    domain_name: drone.kloudcover.com
    hosted_zone: kloudcover.com
    cluster_name: kloudcover
  tasks:
    - shell: git rev-parse HEAD
      register: shaout
    - set_fact:
        sha: "{{shaout.stdout}}"
    - debug: var=sha
    - include: deployment/build_push.yml

    - name: drone stack
      cloudformation:
        stack_name: "{{stackname}}"
        state: present
        region: "{{region}}"
        template: deployment/template.yml
        template_parameters:
          ServiceName: "{{ stackname }}"
          DomainName: "{{ domain_name }}"
          HostedZone: "{{ hosted_zone }}"
          Version: "{{ sha }}"
          ClusterName: "{{ cluster_name }}"
          CertId: "{{cert_id}}"
