---
- hosts: localhost
  gather_facts: false
  vars:
    stackname: drone
    vpc: vpc-849531e0
    region: us-west-2
    version: 0.8.2
    default_service:
      name: drone
      template: template.yml
      cert_id: 727e9900-8f50-4ba8-8bce-09ab4be1e2a2
      domain_name: "drone.kloudcover.com"
      hosted_zone: "kloudcover.com."
  tasks:
    - name: build and push new agent
      shell: ./build.sh

    - name: stack for default resources for alb
      cloudformation:
        stack_name: "{{stackname}}"
        state: present
        region: "{{region}}"
        template: "{{default_service['template']}}"
        template_parameters:
          ServiceName: "{{default_service['name']}}"
          DomainName: "{{default_service['domain_name']}}"
          CertId: "{{default_service['cert_id']}}"
          HostedZone: "{{default_service['hosted_zone']}}"
          Version: "{{version}}"
          ClusterName: "kloudcover"
